
#ifndef SERIALMESSAGECOMMANDS_H_
#define SERIALMESSAGECOMMANDS_H_


#define SERIAL_MESSAGE_CMD_SSID					0x01
#define SERIAL_MESSAGE_CMD_PASSWORD				0x02
#define SERIAL_MESSAGE_CMD_VERSION_FIRMWARE		0x03

#define SERIAL_MESSAGE_CMD_SOY_PROBADOR			0x10
#define SERIAL_MESSAGE_CMD_ACK					0x11
#define SERIAL_MESSAGE_CMD_SOY_PC				0x12
#define SERIAL_MESSAGE_CMD_SOY_WIFICEL100		0x13
#define SERIAL_MESSAGE_CMD_SOY_WIFICEL80		0x14
#define SERIAL_MESSAGE_CMD_SOY_WIFICEL50		0x15
#define SERIAL_MESSAGE_CMD_SOY_COM30			0x16
// WIFICOM100 -> 0x17
#define SERIAL_MESSAGE_CMD_SOY_COM30E    		0x18
#define SERIAL_MESSAGE_CMD_SOY_WIFICEL50E		0x19


#define SERIAL_MESSAGE_CMD_PEDIR_ID				0x20
#define SERIAL_MESSAGE_CMD_ID					0x21
#define SERIAL_MESSAGE_CMD_NO_SERIALIZA			0x22
#define SERIAL_MESSAGE_CMD_MI_ID				0x23

#define SERIAL_MESSAGE_CMD_CLAVE_XTEA			0x30

#define SERIAL_MESSAGE_CMD_IMPRIMIR_QR			0x40

#define SERIAL_MESSAGE_CMD_OK_TECLITA			0x50
#define SERIAL_MESSAGE_CMD_OK_LEDS				0x51
#define SERIAL_MESSAGE_CMD_OK_WIFI				0x52
#define SERIAL_MESSAGE_CMD_OK_BROKER_WIFI		0x53
#define SERIAL_MESSAGE_CMD_OK_EEPROM			0x54
#define SERIAL_MESSAGE_CMD_OK_CELULAR			0x55
#define SERIAL_MESSAGE_CMD_OK_BROKER_CELULAR	0x56


#endif /* SERIALMESSAGECOMMANDS_H_ */